# Site settings
title: Joshua Soileau (swa-low) - Frontend Web Developer
email: joshua.soileau@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Information & tutorials on web development, Magento 1/2, CSS animation, and web stuff.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.joshuasoileau.com" # the base hostname & protocol for your site
twitter_username: joshua_soileau
github_username:  JoshuaSoileau

# Build settings
markdown: kramdown
kramdown:
    highlighter: rouge

# Gems
gems:
  - octopress-autoprefixer